build

diff --git a/build b/build
--- a/build
+++ b/build
@@ -14,7 +14,13 @@ esac
 go mod tidy
 go fmt
 go test ./...
+
+if ! command -v staticcheck &> /dev/null; then
+    echo "==> staticcheck not found. Installing..."
+    go install honnef.co/go/tools/cmd/staticcheck@latest
+fi
 staticcheck ./...
+
 go build -ldflags "-s -w" -o $BIN
 
 # For cross compiling
